services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: rootpass
      DB_DATABASE: scoop

  db:
    image: mysql:8.0.42
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: scoop
      MYSQL_USER: usuario
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/spoon.sql:/docker-entrypoint-initdb.d/spoon.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass

volumes:
  db_data:
