name: ActionsSpoon

on:
  push:
    branches: [ main ]

jobs: 
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout del Repositorio
        uses: actions/checkout@v4
      
      - name: Setup PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Instalar dependencias
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Dar permisos de ejecución a PHPUnit
        run: chmod +x vendor/bin/phpunit

      - name: Hacer commit y push de los cambios
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Changes
          commit_user_name: Itsjulii23 [Github Actions]
          commit_user_email: j.campillosmartinez@gmail.com
